##  Configuration for DiscourseDotNet ##

version: 0.2.{build}-alpha

branches:
  only:
    - master
    - development

os: Windows Server 2012

environment:
  DiscourseApiKey:
    secure: dm10dZqq8Dsx7bl1zmGw2BSBpugrYdbhVP5B65Eepio7r7omzRfAYhd6DcKKlGrNDzGltbdeRQSHuNglTLg0EayjRN7Otd2ZXo5Nk97FPiY

before_build:
  - nuget restore

test:
  assemblies:
     - DiscourseDotNet.Tests.dll
#  categories:
#    only:
#      - Offline
